theme: jekyll-theme-cayman
paginate: 分页数目
title: 博客主题
url: 博客地址(最基础的一级域名)
feed: 订阅地址
author: 作者信息
aubout: 关于作者（描述性）
follow: 社交
indexContent: 在首页是否显示文章详情，true为显示
imagelink: 联系我的个人图片
style: 样式地址
blogName: 博客标题blogDesc: 博客介绍
favicon: favicon地址
theme: 博客的主题
desqus: 社会化评论的id
copyright: 版权